language: node_js

node_js:
  - "8"

services:
  - docker

before_deploy:
  # Run docker build
  - docker build -t benweet/stackedit .
  # Install Helm
  - curl -SLO https://git.io/get_helm.sh
  - chmod 700 get_helm.sh
  - ./get_helm.sh
  - helm init --client-only
  # Make the chart
  - npm run chart

deploy:
  provider: script
  script: bash build/deploy.sh
  on:
    tags: true
